version: 1.0.0
services:
  app:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_PUB_KEY: ${SSH_PUB_KEY}
    image: michsiw439/budoman-backend:1.0.0
    container_name: budoman-backend-app
    ports:
      - 3333:3333
      - 2222:22
    env_file:
      - .env
    networks:
      - budoman-backend
    volumes:
      - .:/budoman-backend
  postgres:
    image: postgres:14
    container_name: budoman-backend-postgres
    ports:
      - 5433:${DATABASE_PORT}
    environment:
      - POSTGRES_USER=${DATABASE_USER_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - budoman-backend
  redis:
    image: redis:7.2.0
    container_name: budoman-backend-redis
    ports:
      - 6379:6379
    networks:
      - budoman-backend
networks:
  budoman-backend:
